---
# tasks file for starthosts
- name: Start Host Controller
  shell: '{{JBOSS_HOME}}/bin/domain.sh --host-config=host-slave.xml &'
  become: yes
  become_method: sudo
  become_user: '{{jboss_user}}'
  async: 20
  poll: 0
