---
- hosts: all
  remote_user: srikrishnanaikb
  become: yes
  vars_prompt:
     - name: "JBOSS_HOME"
       prompt: "Enter Jboss Home directory"
       private: no
       default: "/opt/rh/jboss-eap-7.0"
     - name: "jboss_user"
       prompt: "OS Jboss User "
       private: no
     - name: "eap_profile"
       prompt: "Choose profile \n  1- default\n  2- ha\n  3- full \n  4- full-ha\n"
       private: no
       default: "1"
     - name: "port_offset"
       prompt: "Enter socket binding port offset "
       private: no
       default: "0"
     - name: "jboss_user_type"
       prompt: "What type of user do you wish to add?\n a) Management User (mgmt-users.properties) \n b) Application User (application-users.properties) \n"
       private: no
     - name: "jboss_mgmtapp_user"
       prompt: "Add User "
       private: no
     - name: "jboss_mgmtapp_pwd"
       prompt: "Password "
       private: yes
       confirm: yes
  roles:
     - mgmtappuser
     - standalone
