---
# tasks file for uninstall
- name: Get running processes
  shell: "ps -ef | grep -v grep | grep -w {{jboss_eap_install_dir}} | awk '{print $2}'"
  register: running_processes

- name: Kill running processes
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"

- wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ running_processes.stdout_lines }}"
  ignore_errors: yes
  register: killed_processes

- name: Force kill stuck processes
  shell: "kill -9 {{ item }}"
  with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"
- file:
    path: '{{jdk_install_dir}}'
    state: absent
    mode: 0755
- file:
    path: '{{jboss_eap_install_dir}}'
    state: absent
    mode: 0755

