---
# tasks file for startdomain
- name: Start Domain Controller
  shell: '{{JBOSS_HOME}}/bin/domain.sh --host-config=host-master.xml &'
  become: yes
  become_method: sudo
  become_user: '{{jboss_user}}'
  async: 20
  poll: 0
