- name: "Add Jboss user in the management realm"
  shell: '{{JBOSS_HOME}}/bin/add-user.sh -u {{jboss_mgmtapp_user}} -p {{jboss_mgmtapp_pwd}}'
  become: yes
  become_method: sudo
  become_user: '{{jboss_user}}'
- name: "Password in base64 format"
  shell:  echo '{{jboss_mgmtapp_pwd | b64encode}}'
  register: result
- debug: msg="Use the base64 format password {{result.stdout}} in configuration"
